### ISSUE TITLE
Broken links to images in .md files

### ISSUE THREAD

**Issue by iteles** [SafeLives/roadmap#1]
Images are appearing as broken links in the `.md` files in the roadmap repo.
<img width="382" alt="screen shot 2017-01-29 at 19 37 33" src="https://cloud.githubusercontent.com/assets/4185328/22407239/8675f8fa-e65a-11e6-9502-873356cb8acc.png">

This is due to the link itself expecting one too many levels of folders (`![analysis](../../img/analysis.png)` should be `![analysis](../img/analysis.png)`).

**Comment by SimonLab** [comment]
resolved with #2
